# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170221_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.Client'),
        ),
    ]
