# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_auto_20170222_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtIguala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('art_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_works', to='works.ArtType')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='work_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Iguala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igualas', to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(choices=[(0, 'Diseño'), (1, 'No'), (2, 'Unknown')])),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='works.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('expected_delivery_date', models.DateField()),
                ('brief', models.TextField()),
                ('final_link', models.CharField(max_length=1000)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='clients.Contact')),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.Status')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_works', to=settings.AUTH_USER_MODEL)),
                ('iguala', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.Iguala')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigned_works', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_designers', to='works.Work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.WorkType'),
        ),
        migrations.AddField(
            model_name='statuschange',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='works.Work'),
        ),
        migrations.AddField(
            model_name='file',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='works.Work'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_works', to='works.Work'),
        ),
        migrations.AddField(
            model_name='arttype',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_types', to='works.WorkType'),
        ),
        migrations.AddField(
            model_name='artiguala',
            name='art_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_iguala', to='works.ArtType'),
        ),
        migrations.AddField(
            model_name='artiguala',
            name='iguala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_iguala', to='works.Iguala'),
        ),
    ]
