# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Diseño'), (2, 'Cuentas'), (3, 'Validación'), (4, 'Producción'), (5, 'Por cobrar'), (6, 'Por facturar'), (7, 'Pagado'), (8, 'Terminado')]),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='final_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='workdesigner',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workdesigner',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
