# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20170301_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='iguala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.Iguala'),
        ),
    ]
