# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20170302_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdesigner',
            name='active_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workdesigner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workdesigner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
