# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_worktype_work_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='File', max_length=300),
            preserve_default=False,
        ),
    ]
